version: "3"

services:
  db:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgres-truck-food-finder
    environment:
      - POSTGRES_DB=truck-food-finder
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres-16:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: truck-food-finder:backend
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
